language: node_js
node_js:
  - "0.10"
 #- "0.11" # for some reason 0.11 has a broken npm
  - "0.12"
  - "4.4.3"
  - "5"
  - "5.1"
  - "6"
install: npm install
script: ./node_modules/gulp/bin/gulp.js test
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7961bc762f8b8c0e3122
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
